name: Deploy to PROD S3 Test
on: 
  push: 
    branches:
      - gha-deploy2s3
jobs:
  build:
    name: Build Deploy To PROD S3 Test
    environment: PROD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          yarn install
          yarn workspace @shiksha/common-lib build
          yarn install
          yarn build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
          REACT_APP_SENTRY_DSN_URL: ${{ secrets.REACT_APP_SENTRY_DSN_URL }}
          REACT_APP_SENTRY_ENV: ${{ secrets.REACT_APP_SENTRY_ENV }}
          
      - name: Create Lerna Bundles
        run: |
          sh ./scripts/pack-prod-build.sh

      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: build
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /*
          delete-removed: true
          no-cache: true
          private: true
          filesToInclude: "prod-build/*"
